//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDocTJob
    {
        public string XVJobDocNo { get; set; }
        public Nullable<System.DateTime> XDJobDocDate { get; set; }
        public string XVJobDocStatus { get; set; }
        public string XVCstCode { get; set; }
        public string XVPrjCode { get; set; }
        public string XVCtlCode { get; set; }
        public string XVLmpCode { get; set; }
        public string XVJobProblem { get; set; }
    
        public string XVJobLocation { get; set; }
        public Nullable<System.DateTime> XTJobProblemTime { get; set; }
        public string XVJobResolve { get; set; }
        public Nullable<System.DateTime> XTJobResolveTime { get; set; }
        public Nullable<bool> XBJobIsComplete { get; set; }
        public string XVWhoCreate { get; set; }
        public string XVWhoEdit { get; set; }
        public Nullable<System.DateTime> XTWhenCreate { get; set; }
        public Nullable<System.DateTime> XTWhenEdit { get; set; }
    }
}
