//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMstMLamp
    {
        public string XVLmpCode { get; set; }
        public string XVLmpName { get; set; }
        public string XVLmpDescription { get; set; }
        public string XVLmpSN { get; set; }
        public string XVCtlCode { get; set; }
        public string XVLmpLat { get; set; }
        public string XVLmpLong { get; set; }
        public string XVWhoCreate { get; set; }
        public string XVWhoEdit { get; set; }
        public Nullable<System.DateTime> XTWhenCreate { get; set; }
        public Nullable<System.DateTime> XTWhenEdit { get; set; }
        public Nullable<bool> XBLmpIsWarning { get; set; }
    }
}
