//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSysSSubDistrict
    {
        public string XVSdtCode { get; set; }
        public string XVSdtName { get; set; }
        public string XVSdtNameEng { get; set; }
        public string XVSdtNameWithPrefix { get; set; }
        public string XVSdtNameEngWithPrefix { get; set; }
        public string XVSdtPostCode { get; set; }
        public string XVDstCode { get; set; }
    }
}
