//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSysSDistrict
    {
        public string XVDstCode { get; set; }
        public string XVDstName { get; set; }
        public string XVDstNameEng { get; set; }
        public string XVDstNameWithPrefix { get; set; }
        public string XVDstNameEngWithPrefix { get; set; }
        public string XVPvnCode { get; set; }
    }
}
