//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSysSProvince
    {
        public string XVPvnCode { get; set; }
        public string XVPvnName { get; set; }
        public string XVPvnNameEng { get; set; }
    }
}
