//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTrnTLampUpdate
    {
        public long XIID { get; set; }
        public string XVLmpCode { get; set; }
        public Nullable<System.DateTime> XTStaUpdate { get; set; }
        public Nullable<int> XIStaRelay { get; set; }
        public Nullable<int> XIStaPWM1 { get; set; }
        public Nullable<int> XIStaPWM2 { get; set; }
        public Nullable<int> XIStaSignal { get; set; }
        public Nullable<int> XIStaCurrent { get; set; }
        public Nullable<int> XIStaAmLight { get; set; }
        public Nullable<int> XIStaMode { get; set; }
    }
}
