//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTrnTWarning
    {
        public long XIID { get; set; }
        public string XVLmpCode { get; set; }
        public string XVWanType { get; set; }
        public Nullable<System.DateTime> XTWanTime { get; set; }
        public string XVWanValue { get; set; }
        public Nullable<bool> XBWanIsNotify { get; set; }
    }
}
