//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMstMCustomer
    {
        public string XVCstCode { get; set; }
        public string XVCstName { get; set; }
        public string XVCstAddress { get; set; }
        public string XVCstPhone { get; set; }
        public string XVCstEmail { get; set; }
        public string XVWhoCreate { get; set; }
        public string XVWhoEdit { get; set; }
        public Nullable<System.DateTime> XTWhenCreate { get; set; }
        public Nullable<System.DateTime> XTWhenEdit { get; set; }
    }
}
