//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMstMController
    {
        public string XVCtlCode { get; set; }
        public string XVCtlName { get; set; }
        public string XVCtlDescription { get; set; }
        public string XVCtlSN { get; set; }
        public string XVPrjCode { get; set; }
        public string XVCtlLat { get; set; }
        public string XVCtlLong { get; set; }
        public string XVWhoCreate { get; set; }
        public string XVWhoEdit { get; set; }
        public Nullable<System.DateTime> XTWhenCreate { get; set; }
        public Nullable<System.DateTime> XTWhenEdit { get; set; }
        public string XVCtlPhone { get; set; }
        public Nullable<int> XICtlLampQty { get; set; }
        public Nullable<double> XFCtlAmpMin { get; set; }
        public Nullable<double> XFCtlAmpMax { get; set; }
        public string XVBoxNo { get; set; }
        public string XVBoxKmFrom { get; set; }
        public string XVBoxKmTo { get; set; }
    }
}
