//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWL_AdAm_DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LampStatus
    {
        public string XVCstCode { get; set; }
        public string XVCstName { get; set; }
        public string XVPrjCode { get; set; }
        public string XVPrjName { get; set; }
        public string XVPrjType { get; set; }
        public string XVCtlCode { get; set; }
        public string XVCtlName { get; set; }
        public string XVCtlSN { get; set; }
        public string XVCtlLat { get; set; }
        public string XVCtlLong { get; set; }
        public string XVLmpCode { get; set; }
        public string XVLmpName { get; set; }
        public string XVLmpSN { get; set; }
        public string XVLmpLat { get; set; }
        public string XVLmpLong { get; set; }
        public Nullable<System.DateTime> XTStaUpdate { get; set; }
        public Nullable<int> XIStaRelay { get; set; }
        public Nullable<int> XIStaPWM1 { get; set; }
        public Nullable<int> XIStaPWM2 { get; set; }
        public Nullable<int> XIStaSignal { get; set; }
        public Nullable<int> XIStaCurrent { get; set; }
        public Nullable<int> XIStaAmLight { get; set; }
        public Nullable<int> XIStaMode { get; set; }
    }
}
